// <auto-generated />
using CustomersAPIProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomersAPIProject.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240919142341_SeedCustomersTable")]
    partial class SeedCustomersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomersAPIProject.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "1 Wall Street",
                            Email = "msmith@gmail.com",
                            Name = "Mike Smith",
                            Phone = "0800 750 2219"
                        },
                        new
                        {
                            CustomerID = 2,
                            Address = "10 Swiss Cottage Street",
                            Email = "jsmith@gmail.com",
                            Name = "John Hill",
                            Phone = "0800 750 2219"
                        },
                        new
                        {
                            CustomerID = 3,
                            Address = "15 Logan Road",
                            Email = "tdavis@gmail.com",
                            Name = "Tom Davis",
                            Phone = "0800 750 2219"
                        },
                        new
                        {
                            CustomerID = 4,
                            Address = "12 Forest Street",
                            Email = "willb@yahoo.com",
                            Name = "Will Brown",
                            Phone = "0800 750 2219"
                        },
                        new
                        {
                            CustomerID = 5,
                            Address = "20 Fenchurch Road",
                            Email = "jsmith@yahoo.com",
                            Name = "Jess Smith",
                            Phone = "0800 750 2219"
                        },
                        new
                        {
                            CustomerID = 6,
                            Address = "25 Greenhill Lane",
                            Email = "jnmiills@gmail.com",
                            Name = "Kate Mills",
                            Phone = "0800 750 2219"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
